### ISSUE TITLE
Bastion Security Group

### ISSUE THREAD

**Issue by nicklester** [cfn-modules/ssh-bastion#14]
Hello,

Is there a reason the security group created for the Bastion doesn't use the client-sg template? Is this for a different purpose?

The reason I ask is I would like to create the bastion and export the stack of the created security group for the ssh-bastion module so I can use it to grant access to AWS resources from the bastion host. Unless I am misunderstanding the use case?

**Comment by michaelwittig** [comment]
hi!

I agree that the idea of client-sg and bastion overlaps.

the idea of the bastion is this: an admin wants to access the system.
the idea of client-sg is: a system wants to access another system.

What's your use case? :)

**Comment by nicklester** [comment]
Hi again :)

MSK cluster. Admin wants to access Kafka. MSK has been configured to allow access to specific ports to a particular security group. I need to add that security group to the bastion host so Kafka will permit ingress...

**Comment by michaelwittig** [comment]
I see. All database modules come with a `BastionModule` parameter for this purpose.

**Comment by nicklester** [comment]
You will see what I mean if you look at my fork:

https://github.com/nicklester/ssh-bastion/blob/1c0b5f9c54a31f530f64b3bc4933eb70954d22c4/module.yml#L53

https://github.com/nicklester/ssh-bastion/blob/1c0b5f9c54a31f530f64b3bc4933eb70954d22c4/module.yml#L315

**Comment by nicklester** [comment]
I'll see how that is implemented and see if it could work for my MSK module. Also works for Fargate containers?

**Comment by michaelwittig** [comment]
one example from an RDS instance:

https://github.com/cfn-modules/rds-instance/blob/master/module.yml#L22
https://github.com/cfn-modules/rds-instance/blob/master/module.yml#L31

I hope that helps.

**Comment by nicklester** [comment]
OK - before I delete my fork :)

Is there any provision for Fargate?

**Comment by michaelwittig** [comment]
I'm not sure if I get your question: Are you asking if there is a ssh-bastion like module where the bastion host runs on Fargate?

**Comment by nicklester** [comment]
Hi - no where the bastion host can jump to a fargate container..

**Comment by michaelwittig** [comment]
I see. Looks like we should add the BastionModule parameter to the fargate-service module?

**Comment by nicklester** [comment]
Im thinking that. I'm happy to take a look and submit a PR if I can find an
answer?

**Comment by nicklester** [comment]
I've looked a bit more into it. I'm not certain this is going to be a good idea at all thinking about it. Would end up having to host an sash daemon on the container - breaking the one process per container paradigm + certainly introducing security issues. I'll close this down!
